package com.choicetrax.server.util.jdbc;

import java.sql.*;

import com.choicetrax.client.util.exception.ChoicetraxDatabaseException;

public interface DBResource 
{
	
	void clearParameters() throws ChoicetraxDatabaseException;
	
	void close() throws ChoicetraxDatabaseException;
	
	void commit() throws ChoicetraxDatabaseException;
	
	ResultSet executeQuery() throws ChoicetraxDatabaseException;
	
	ResultSet executeQuery(String sql) throws ChoicetraxDatabaseException;
	
	int executeUpdate() throws ChoicetraxDatabaseException;
	
	int executeUpdate(String sql) throws ChoicetraxDatabaseException;
	
	int executeUpdate(String sql, int autoGeneratedKeys) throws ChoicetraxDatabaseException;
	
	ResultSet getGeneratedKeys() throws ChoicetraxDatabaseException;
	
	void prepareStatement(String sql) throws ChoicetraxDatabaseException;
	
	void rollback() throws ChoicetraxDatabaseException;
	
	void setAutoCommit(boolean state) throws ChoicetraxDatabaseException;
	
	void setBigDecimal(int i, java.math.BigDecimal value) throws ChoicetraxDatabaseException;
	
	void setBoolean( int i, boolean b ) throws ChoicetraxDatabaseException;
	
	void setDate( int i, java.sql.Date d ) throws ChoicetraxDatabaseException;
	
	void setDouble( int i, double d ) throws ChoicetraxDatabaseException;
	
	void setFloat( int i, float f ) throws ChoicetraxDatabaseException;
	
	void setInt( int i, int value ) throws ChoicetraxDatabaseException;
	
	void setLong( int i, long value ) throws ChoicetraxDatabaseException;
	
	void setObject( int i, Object o, int sqlType, int scale ) throws ChoicetraxDatabaseException;
	
	void setString( int i, String s ) throws ChoicetraxDatabaseException;
	
	void setTimestamp( int i, java.sql.Timestamp t ) throws ChoicetraxDatabaseException;
	
	void shutdown() throws ChoicetraxDatabaseException;
	
	boolean getAutoCommit() throws ChoicetraxDatabaseException;
	
	void setReadOnly( boolean b ) throws ChoicetraxDatabaseException;
	
	boolean isReadOnly() throws ChoicetraxDatabaseException;

}
